[character]
success_symbol = "[âœ](bold green)"
error_symbol = "[âœ](bold red)"

[username]
format = "[$user]($style)"

[hostname]
format = ":[$hostname]($style) "

# configure directory
[directory]
read_only = "ï€£ "
truncation_length = 10
truncate_to_repo = true # truncates directory to root folder if in github repo
style = "bold italic blue"

# [cmd_duration]
# min_time = 4
# show_milliseconds = false
# disabled = false
# style = "bold italic red"

[aws]
symbol = "îŒ½ "

[conda]
symbol = "ï„Œ "

[docker_context]
symbol = "ïŒˆ "
format = "via [$symbol$context]($style) "
style = "blue bold"
only_with_files = true
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
detect_folders = []
disabled = false

[elixir]
symbol = "î˜­ "

[git_branch]
symbol = "ï˜ "

[git_status]
format = '([$all_status$ahead_behind]($style)) '
# conflicted = '\[âœ˜ [$count](bright-white bold)\]'
# ahead = '\[[â‡¡](bright-blue)[$count](bright-white bold)\]'
# behind = '\[[â‡£](white)[$count](bright-white bold)\]'
# diverged = '\[[îœ¨ ](purple)|[â‡¡](bright-blue)[$ahead_count](bright-white bold)[â‡£](white)[$behind_count](bright-white)\]'
# untracked = '\[ï”© [$count](bright-white bold)\]'
# stashed = '\[[ğŸ“¦](bright-yellow)[$count](bright-white bold)\]'
# modified = '\[[ï„ ](bright-bright-yellow)[$count](bright-white bold)\]'
# staged = '\[[ï† ](bright-green)[$count](bright-white bold)\]'
# renamed = '\[[ï‘š ](bright-cyan) [$count](bright-white bold)\]'
# deleted = '\[ï€” [$count](bright-white bold)\]'

conflicted = '\[[îœ§](red)[$count](bright-white bold)\]'
ahead = '\[[â‡¡](bright-blue)[$count](bright-white bold)\]'
behind = '\[[â‡£](bright-blue)[$count](bright-white bold)\]'
diverged = '\[[îœ¨ ](bright-green)|[â‡¡](bright-blue)[$ahead_count](bright-white bold)[â‡£](bright-blue)[$behind_count](bright-white)\]'
untracked = '\[[?](bright-bright-yellow)[$count](bright-white bold)\]'
stashed = '\[[\$](bright-yellow)[$count](bright-white bold)\]'
modified = '\[[~](bright-yellow)[$count](bright-white bold)\]'
staged = '\[[âœ“](bright-yellow)[$count](bright-white bold)\]'
renamed = '\[[Â»](bright-yellow) [$count](bright-white bold)\]'
deleted = '\[[-](bright-yellow)[$count](bright-white bold)\]'

[golang]
symbol = "î˜§ "

[java]
symbol = "î‰– "

[julia]
symbol = "î˜¤ "

[lua]
symbol = "î˜  "

[ocaml]
symbol = "î™º "

[package]
symbol = "ï’‡ "

[perl]
symbol = "î™¾ "

[php]
symbol = "î˜ˆ "

[python]
symbol = "î˜† "
#pyenv_version_name = true
format = 'via [${symbol}(${version} )(\($virtualenv\) )]($style)'
style = "bold bright-yellow"
pyenv_prefix = "venv "
python_binary = ["./venv/bin/python", "python", "python3", "python2"]
detect_extensions = ["py"]
version_format = "v${raw}"

[ruby]
symbol = "î‘ "

[rust]
symbol = "îš‹ "

[scala]
symbol = "îœ· "

[shlvl]
symbol = "ï„  "

# [swift]
# symbol = "î• "

[nodejs]
symbol = "îœ˜ "
format = "via [${symbol}$version](bold green) "
detect_files = ["package.json", ".node-version"]
detect_folders = ["node_modules"]
